services:
  docs:
    image: test_django_ninja_local_docs
    container_name: test_django_ninja_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./test_django_ninja:/app/test_django_ninja:z
    ports:
      - '9000:9000'
    command: /start-docs
